// AUTO-GENERATED from FIFA 2026 Regulations Annex C — DO NOT HAND-EDIT.
// 495 rows mapping advancing 3rd-placer groups → which slot each fills.
// Source: FIFA World Cup 2026 Regulations (v15), pages 80-99.

/** Slot map: T_for_X (the group winner X faces) → group letter whose 3rd-placer fills it. */
export type ThirdPlaceAssignment = { A: string; B: string; D: string; E: string; G: string; I: string; K: string; L: string };

/**
 * Lookup keyed on sorted advancing-3rd-placer groups (e.g., "CDEFGHJK" if those 8 groups' 3rd-placers advance).
 */
export const FIFA_THIRD_PLACE_MATRIX: Record<string, ThirdPlaceAssignment> = {
  'EFGHIJKL': { A: 'E', B: 'J', D: 'I', E: 'F', G: 'H', I: 'G', K: 'L', L: 'K' }, // row 1
  'DFGHIJKL': { A: 'H', B: 'G', D: 'I', E: 'D', G: 'J', I: 'F', K: 'L', L: 'K' }, // row 2
  'DEGHIJKL': { A: 'E', B: 'J', D: 'I', E: 'D', G: 'H', I: 'G', K: 'L', L: 'K' }, // row 3
  'DEFHIJKL': { A: 'E', B: 'J', D: 'I', E: 'D', G: 'H', I: 'F', K: 'L', L: 'K' }, // row 4
  'DEFGIJKL': { A: 'E', B: 'G', D: 'I', E: 'D', G: 'J', I: 'F', K: 'L', L: 'K' }, // row 5
  'DEFGHJKL': { A: 'E', B: 'G', D: 'J', E: 'D', G: 'H', I: 'F', K: 'L', L: 'K' }, // row 6
  'DEFGHIKL': { A: 'E', B: 'G', D: 'I', E: 'D', G: 'H', I: 'F', K: 'L', L: 'K' }, // row 7
  'DEFGHIJL': { A: 'E', B: 'G', D: 'J', E: 'D', G: 'H', I: 'F', K: 'L', L: 'I' }, // row 8
  'DEFGHIJK': { A: 'E', B: 'G', D: 'J', E: 'D', G: 'H', I: 'F', K: 'I', L: 'K' }, // row 9
  'CFGHIJKL': { A: 'H', B: 'G', D: 'I', E: 'C', G: 'J', I: 'F', K: 'L', L: 'K' }, // row 10
  'CEGHIJKL': { A: 'E', B: 'J', D: 'I', E: 'C', G: 'H', I: 'G', K: 'L', L: 'K' }, // row 11
  'CEFHIJKL': { A: 'E', B: 'J', D: 'I', E: 'C', G: 'H', I: 'F', K: 'L', L: 'K' }, // row 12
  'CEFGIJKL': { A: 'E', B: 'G', D: 'I', E: 'C', G: 'J', I: 'F', K: 'L', L: 'K' }, // row 13
  'CEFGHJKL': { A: 'E', B: 'G', D: 'J', E: 'C', G: 'H', I: 'F', K: 'L', L: 'K' }, // row 14
  'CEFGHIKL': { A: 'E', B: 'G', D: 'I', E: 'C', G: 'H', I: 'F', K: 'L', L: 'K' }, // row 15
  'CEFGHIJL': { A: 'E', B: 'G', D: 'J', E: 'C', G: 'H', I: 'F', K: 'L', L: 'I' }, // row 16
  'CEFGHIJK': { A: 'E', B: 'G', D: 'J', E: 'C', G: 'H', I: 'F', K: 'I', L: 'K' }, // row 17
  'CDGHIJKL': { A: 'H', B: 'G', D: 'I', E: 'C', G: 'J', I: 'D', K: 'L', L: 'K' }, // row 18
  'CDFHIJKL': { A: 'C', B: 'J', D: 'I', E: 'D', G: 'H', I: 'F', K: 'L', L: 'K' }, // row 19
  'CDFGIJKL': { A: 'C', B: 'G', D: 'I', E: 'D', G: 'J', I: 'F', K: 'L', L: 'K' }, // row 20
  'CDFGHJKL': { A: 'C', B: 'G', D: 'J', E: 'D', G: 'H', I: 'F', K: 'L', L: 'K' }, // row 21
  'CDFGHIKL': { A: 'C', B: 'G', D: 'I', E: 'D', G: 'H', I: 'F', K: 'L', L: 'K' }, // row 22
  'CDFGHIJL': { A: 'C', B: 'G', D: 'J', E: 'D', G: 'H', I: 'F', K: 'L', L: 'I' }, // row 23
  'CDFGHIJK': { A: 'C', B: 'G', D: 'J', E: 'D', G: 'H', I: 'F', K: 'I', L: 'K' }, // row 24
  'CDEHIJKL': { A: 'E', B: 'J', D: 'I', E: 'C', G: 'H', I: 'D', K: 'L', L: 'K' }, // row 25
  'CDEGIJKL': { A: 'E', B: 'G', D: 'I', E: 'C', G: 'J', I: 'D', K: 'L', L: 'K' }, // row 26
  'CDEGHJKL': { A: 'E', B: 'G', D: 'J', E: 'C', G: 'H', I: 'D', K: 'L', L: 'K' }, // row 27
  'CDEGHIKL': { A: 'E', B: 'G', D: 'I', E: 'C', G: 'H', I: 'D', K: 'L', L: 'K' }, // row 28
  'CDEGHIJL': { A: 'E', B: 'G', D: 'J', E: 'C', G: 'H', I: 'D', K: 'L', L: 'I' }, // row 29
  'CDEGHIJK': { A: 'E', B: 'G', D: 'J', E: 'C', G: 'H', I: 'D', K: 'I', L: 'K' }, // row 30
  'CDEFIJKL': { A: 'C', B: 'J', D: 'E', E: 'D', G: 'I', I: 'F', K: 'L', L: 'K' }, // row 31
  'CDEFHJKL': { A: 'C', B: 'J', D: 'E', E: 'D', G: 'H', I: 'F', K: 'L', L: 'K' }, // row 32
  'CDEFHIKL': { A: 'C', B: 'E', D: 'I', E: 'D', G: 'H', I: 'F', K: 'L', L: 'K' }, // row 33
  'CDEFHIJL': { A: 'C', B: 'J', D: 'E', E: 'D', G: 'H', I: 'F', K: 'L', L: 'I' }, // row 34
  'CDEFHIJK': { A: 'C', B: 'J', D: 'E', E: 'D', G: 'H', I: 'F', K: 'I', L: 'K' }, // row 35
  'CDEFGJKL': { A: 'C', B: 'G', D: 'E', E: 'D', G: 'J', I: 'F', K: 'L', L: 'K' }, // row 36
  'CDEFGIKL': { A: 'C', B: 'G', D: 'E', E: 'D', G: 'I', I: 'F', K: 'L', L: 'K' }, // row 37
  'CDEFGIJL': { A: 'C', B: 'G', D: 'E', E: 'D', G: 'J', I: 'F', K: 'L', L: 'I' }, // row 38
  'CDEFGIJK': { A: 'C', B: 'G', D: 'E', E: 'D', G: 'J', I: 'F', K: 'I', L: 'K' }, // row 39
  'CDEFGHKL': { A: 'C', B: 'G', D: 'E', E: 'D', G: 'H', I: 'F', K: 'L', L: 'K' }, // row 40
  'CDEFGHJL': { A: 'C', B: 'G', D: 'J', E: 'D', G: 'H', I: 'F', K: 'L', L: 'E' }, // row 41
  'CDEFGHJK': { A: 'C', B: 'G', D: 'J', E: 'D', G: 'H', I: 'F', K: 'E', L: 'K' }, // row 42
  'CDEFGHIL': { A: 'C', B: 'G', D: 'E', E: 'D', G: 'H', I: 'F', K: 'L', L: 'I' }, // row 43
  'CDEFGHIK': { A: 'C', B: 'G', D: 'E', E: 'D', G: 'H', I: 'F', K: 'I', L: 'K' }, // row 44
  'CDEFGHIJ': { A: 'C', B: 'G', D: 'J', E: 'D', G: 'H', I: 'F', K: 'E', L: 'I' }, // row 45
  'BFGHIJKL': { A: 'H', B: 'J', D: 'B', E: 'F', G: 'I', I: 'G', K: 'L', L: 'K' }, // row 46
  'BEGHIJKL': { A: 'E', B: 'J', D: 'I', E: 'B', G: 'H', I: 'G', K: 'L', L: 'K' }, // row 47
  'BEFHIJKL': { A: 'E', B: 'J', D: 'B', E: 'F', G: 'I', I: 'H', K: 'L', L: 'K' }, // row 48
  'BEFGIJKL': { A: 'E', B: 'J', D: 'B', E: 'F', G: 'I', I: 'G', K: 'L', L: 'K' }, // row 49
  'BEFGHJKL': { A: 'E', B: 'J', D: 'B', E: 'F', G: 'H', I: 'G', K: 'L', L: 'K' }, // row 50
  'BEFGHIKL': { A: 'E', B: 'G', D: 'B', E: 'F', G: 'I', I: 'H', K: 'L', L: 'K' }, // row 51
  'BEFGHIJL': { A: 'E', B: 'J', D: 'B', E: 'F', G: 'H', I: 'G', K: 'L', L: 'I' }, // row 52
  'BEFGHIJK': { A: 'E', B: 'J', D: 'B', E: 'F', G: 'H', I: 'G', K: 'I', L: 'K' }, // row 53
  'BDGHIJKL': { A: 'H', B: 'J', D: 'B', E: 'D', G: 'I', I: 'G', K: 'L', L: 'K' }, // row 54
  'BDFHIJKL': { A: 'H', B: 'J', D: 'B', E: 'D', G: 'I', I: 'F', K: 'L', L: 'K' }, // row 55
  'BDFGIJKL': { A: 'I', B: 'G', D: 'B', E: 'D', G: 'J', I: 'F', K: 'L', L: 'K' }, // row 56
  'BDFGHJKL': { A: 'H', B: 'G', D: 'B', E: 'D', G: 'J', I: 'F', K: 'L', L: 'K' }, // row 57
  'BDFGHIKL': { A: 'H', B: 'G', D: 'B', E: 'D', G: 'I', I: 'F', K: 'L', L: 'K' }, // row 58
  'BDFGHIJL': { A: 'H', B: 'G', D: 'B', E: 'D', G: 'J', I: 'F', K: 'L', L: 'I' }, // row 59
  'BDFGHIJK': { A: 'H', B: 'G', D: 'B', E: 'D', G: 'J', I: 'F', K: 'I', L: 'K' }, // row 60
  'BDEHIJKL': { A: 'E', B: 'J', D: 'B', E: 'D', G: 'I', I: 'H', K: 'L', L: 'K' }, // row 61
  'BDEGIJKL': { A: 'E', B: 'J', D: 'B', E: 'D', G: 'I', I: 'G', K: 'L', L: 'K' }, // row 62
  'BDEGHJKL': { A: 'E', B: 'J', D: 'B', E: 'D', G: 'H', I: 'G', K: 'L', L: 'K' }, // row 63
  'BDEGHIKL': { A: 'E', B: 'G', D: 'B', E: 'D', G: 'I', I: 'H', K: 'L', L: 'K' }, // row 64
  'BDEGHIJL': { A: 'E', B: 'J', D: 'B', E: 'D', G: 'H', I: 'G', K: 'L', L: 'I' }, // row 65
  'BDEGHIJK': { A: 'E', B: 'J', D: 'B', E: 'D', G: 'H', I: 'G', K: 'I', L: 'K' }, // row 66
  'BDEFIJKL': { A: 'E', B: 'J', D: 'B', E: 'D', G: 'I', I: 'F', K: 'L', L: 'K' }, // row 67
  'BDEFHJKL': { A: 'E', B: 'J', D: 'B', E: 'D', G: 'H', I: 'F', K: 'L', L: 'K' }, // row 68
  'BDEFHIKL': { A: 'E', B: 'I', D: 'B', E: 'D', G: 'H', I: 'F', K: 'L', L: 'K' }, // row 69
  'BDEFHIJL': { A: 'E', B: 'J', D: 'B', E: 'D', G: 'H', I: 'F', K: 'L', L: 'I' }, // row 70
  'BDEFHIJK': { A: 'E', B: 'J', D: 'B', E: 'D', G: 'H', I: 'F', K: 'I', L: 'K' }, // row 71
  'BDEFGJKL': { A: 'E', B: 'G', D: 'B', E: 'D', G: 'J', I: 'F', K: 'L', L: 'K' }, // row 72
  'BDEFGIKL': { A: 'E', B: 'G', D: 'B', E: 'D', G: 'I', I: 'F', K: 'L', L: 'K' }, // row 73
  'BDEFGIJL': { A: 'E', B: 'G', D: 'B', E: 'D', G: 'J', I: 'F', K: 'L', L: 'I' }, // row 74
  'BDEFGIJK': { A: 'E', B: 'G', D: 'B', E: 'D', G: 'J', I: 'F', K: 'I', L: 'K' }, // row 75
  'BDEFGHKL': { A: 'E', B: 'G', D: 'B', E: 'D', G: 'H', I: 'F', K: 'L', L: 'K' }, // row 76
  'BDEFGHJL': { A: 'H', B: 'G', D: 'B', E: 'D', G: 'J', I: 'F', K: 'L', L: 'E' }, // row 77
  'BDEFGHJK': { A: 'H', B: 'G', D: 'B', E: 'D', G: 'J', I: 'F', K: 'E', L: 'K' }, // row 78
  'BDEFGHIL': { A: 'E', B: 'G', D: 'B', E: 'D', G: 'H', I: 'F', K: 'L', L: 'I' }, // row 79
  'BDEFGHIK': { A: 'E', B: 'G', D: 'B', E: 'D', G: 'H', I: 'F', K: 'I', L: 'K' }, // row 80
  'BDEFGHIJ': { A: 'H', B: 'G', D: 'B', E: 'D', G: 'J', I: 'F', K: 'E', L: 'I' }, // row 81
  'BCGHIJKL': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'I', I: 'G', K: 'L', L: 'K' }, // row 82
  'BCFHIJKL': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'I', I: 'F', K: 'L', L: 'K' }, // row 83
  'BCFGIJKL': { A: 'I', B: 'G', D: 'B', E: 'C', G: 'J', I: 'F', K: 'L', L: 'K' }, // row 84
  'BCFGHJKL': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'J', I: 'F', K: 'L', L: 'K' }, // row 85
  'BCFGHIKL': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'I', I: 'F', K: 'L', L: 'K' }, // row 86
  'BCFGHIJL': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'J', I: 'F', K: 'L', L: 'I' }, // row 87
  'BCFGHIJK': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'J', I: 'F', K: 'I', L: 'K' }, // row 88
  'BCEHIJKL': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'I', I: 'H', K: 'L', L: 'K' }, // row 89
  'BCEGIJKL': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'I', I: 'G', K: 'L', L: 'K' }, // row 90
  'BCEGHJKL': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'H', I: 'G', K: 'L', L: 'K' }, // row 91
  'BCEGHIKL': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'I', I: 'H', K: 'L', L: 'K' }, // row 92
  'BCEGHIJL': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'H', I: 'G', K: 'L', L: 'I' }, // row 93
  'BCEGHIJK': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'H', I: 'G', K: 'I', L: 'K' }, // row 94
  'BCEFIJKL': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'I', I: 'F', K: 'L', L: 'K' }, // row 95
  'BCEFHJKL': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'H', I: 'F', K: 'L', L: 'K' }, // row 96
  'BCEFHIKL': { A: 'E', B: 'I', D: 'B', E: 'C', G: 'H', I: 'F', K: 'L', L: 'K' }, // row 97
  'BCEFHIJL': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'H', I: 'F', K: 'L', L: 'I' }, // row 98
  'BCEFHIJK': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'H', I: 'F', K: 'I', L: 'K' }, // row 99
  'BCEFGJKL': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'J', I: 'F', K: 'L', L: 'K' }, // row 100
  'BCEFGIKL': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'I', I: 'F', K: 'L', L: 'K' }, // row 101
  'BCEFGIJL': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'J', I: 'F', K: 'L', L: 'I' }, // row 102
  'BCEFGIJK': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'J', I: 'F', K: 'I', L: 'K' }, // row 103
  'BCEFGHKL': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'H', I: 'F', K: 'L', L: 'K' }, // row 104
  'BCEFGHJL': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'J', I: 'F', K: 'L', L: 'E' }, // row 105
  'BCEFGHJK': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'J', I: 'F', K: 'E', L: 'K' }, // row 106
  'BCEFGHIL': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'H', I: 'F', K: 'L', L: 'I' }, // row 107
  'BCEFGHIK': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'H', I: 'F', K: 'I', L: 'K' }, // row 108
  'BCEFGHIJ': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'J', I: 'F', K: 'E', L: 'I' }, // row 109
  'BCDHIJKL': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'I', I: 'D', K: 'L', L: 'K' }, // row 110
  'BCDGIJKL': { A: 'I', B: 'G', D: 'B', E: 'C', G: 'J', I: 'D', K: 'L', L: 'K' }, // row 111
  'BCDGHJKL': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'J', I: 'D', K: 'L', L: 'K' }, // row 112
  'BCDGHIKL': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'I', I: 'D', K: 'L', L: 'K' }, // row 113
  'BCDGHIJL': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'J', I: 'D', K: 'L', L: 'I' }, // row 114
  'BCDGHIJK': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'J', I: 'D', K: 'I', L: 'K' }, // row 115
  'BCDFIJKL': { A: 'C', B: 'J', D: 'B', E: 'D', G: 'I', I: 'F', K: 'L', L: 'K' }, // row 116
  'BCDFHJKL': { A: 'C', B: 'J', D: 'B', E: 'D', G: 'H', I: 'F', K: 'L', L: 'K' }, // row 117
  'BCDFHIKL': { A: 'C', B: 'I', D: 'B', E: 'D', G: 'H', I: 'F', K: 'L', L: 'K' }, // row 118
  'BCDFHIJL': { A: 'C', B: 'J', D: 'B', E: 'D', G: 'H', I: 'F', K: 'L', L: 'I' }, // row 119
  'BCDFHIJK': { A: 'C', B: 'J', D: 'B', E: 'D', G: 'H', I: 'F', K: 'I', L: 'K' }, // row 120
  'BCDFGJKL': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'J', I: 'F', K: 'L', L: 'K' }, // row 121
  'BCDFGIKL': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'I', I: 'F', K: 'L', L: 'K' }, // row 122
  'BCDFGIJL': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'J', I: 'F', K: 'L', L: 'I' }, // row 123
  'BCDFGIJK': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'J', I: 'F', K: 'I', L: 'K' }, // row 124
  'BCDFGHKL': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'H', I: 'F', K: 'L', L: 'K' }, // row 125
  'BCDFGHJL': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'H', I: 'F', K: 'L', L: 'J' }, // row 126
  'BCDFGHJK': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'J', I: 'F', K: 'D', L: 'K' }, // row 127
  'BCDFGHIL': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'H', I: 'F', K: 'L', L: 'I' }, // row 128
  'BCDFGHIK': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'H', I: 'F', K: 'I', L: 'K' }, // row 129
  'BCDFGHIJ': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'J', I: 'F', K: 'D', L: 'I' }, // row 130
  'BCDEIJKL': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'I', I: 'D', K: 'L', L: 'K' }, // row 131
  'BCDEHJKL': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'H', I: 'D', K: 'L', L: 'K' }, // row 132
  'BCDEHIKL': { A: 'E', B: 'I', D: 'B', E: 'C', G: 'H', I: 'D', K: 'L', L: 'K' }, // row 133
  'BCDEHIJL': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'H', I: 'D', K: 'L', L: 'I' }, // row 134
  'BCDEHIJK': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'H', I: 'D', K: 'I', L: 'K' }, // row 135
  'BCDEGJKL': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'J', I: 'D', K: 'L', L: 'K' }, // row 136
  'BCDEGIKL': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'I', I: 'D', K: 'L', L: 'K' }, // row 137
  'BCDEGIJL': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'J', I: 'D', K: 'L', L: 'I' }, // row 138
  'BCDEGIJK': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'J', I: 'D', K: 'I', L: 'K' }, // row 139
  'BCDEGHKL': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'H', I: 'D', K: 'L', L: 'K' }, // row 140
  'BCDEGHJL': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'J', I: 'D', K: 'L', L: 'E' }, // row 141
  'BCDEGHJK': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'J', I: 'D', K: 'E', L: 'K' }, // row 142
  'BCDEGHIL': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'H', I: 'D', K: 'L', L: 'I' }, // row 143
  'BCDEGHIK': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'H', I: 'D', K: 'I', L: 'K' }, // row 144
  'BCDEGHIJ': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'J', I: 'D', K: 'E', L: 'I' }, // row 145
  'BCDEFJKL': { A: 'C', B: 'J', D: 'B', E: 'D', G: 'E', I: 'F', K: 'L', L: 'K' }, // row 146
  'BCDEFIKL': { A: 'C', B: 'E', D: 'B', E: 'D', G: 'I', I: 'F', K: 'L', L: 'K' }, // row 147
  'BCDEFIJL': { A: 'C', B: 'J', D: 'B', E: 'D', G: 'E', I: 'F', K: 'L', L: 'I' }, // row 148
  'BCDEFIJK': { A: 'C', B: 'J', D: 'B', E: 'D', G: 'E', I: 'F', K: 'I', L: 'K' }, // row 149
  'BCDEFHKL': { A: 'C', B: 'E', D: 'B', E: 'D', G: 'H', I: 'F', K: 'L', L: 'K' }, // row 150
  'BCDEFHJL': { A: 'C', B: 'J', D: 'B', E: 'D', G: 'H', I: 'F', K: 'L', L: 'E' }, // row 151
  'BCDEFHJK': { A: 'C', B: 'J', D: 'B', E: 'D', G: 'H', I: 'F', K: 'E', L: 'K' }, // row 152
  'BCDEFHIL': { A: 'C', B: 'E', D: 'B', E: 'D', G: 'H', I: 'F', K: 'L', L: 'I' }, // row 153
  'BCDEFHIK': { A: 'C', B: 'E', D: 'B', E: 'D', G: 'H', I: 'F', K: 'I', L: 'K' }, // row 154
  'BCDEFHIJ': { A: 'C', B: 'J', D: 'B', E: 'D', G: 'H', I: 'F', K: 'E', L: 'I' }, // row 155
  'BCDEFGKL': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'E', I: 'F', K: 'L', L: 'K' }, // row 156
  'BCDEFGJL': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'J', I: 'F', K: 'L', L: 'E' }, // row 157
  'BCDEFGJK': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'J', I: 'F', K: 'E', L: 'K' }, // row 158
  'BCDEFGIL': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'E', I: 'F', K: 'L', L: 'I' }, // row 159
  'BCDEFGIK': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'E', I: 'F', K: 'I', L: 'K' }, // row 160
  'BCDEFGIJ': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'J', I: 'F', K: 'E', L: 'I' }, // row 161
  'BCDEFGHL': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'H', I: 'F', K: 'L', L: 'E' }, // row 162
  'BCDEFGHK': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'H', I: 'F', K: 'E', L: 'K' }, // row 163
  'BCDEFGHJ': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'J', I: 'F', K: 'D', L: 'E' }, // row 164
  'BCDEFGHI': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'H', I: 'F', K: 'E', L: 'I' }, // row 165
  'AFGHIJKL': { A: 'H', B: 'J', D: 'I', E: 'F', G: 'A', I: 'G', K: 'L', L: 'K' }, // row 166
  'AEGHIJKL': { A: 'E', B: 'J', D: 'I', E: 'A', G: 'H', I: 'G', K: 'L', L: 'K' }, // row 167
  'AEFHIJKL': { A: 'E', B: 'J', D: 'I', E: 'F', G: 'A', I: 'H', K: 'L', L: 'K' }, // row 168
  'AEFGIJKL': { A: 'E', B: 'J', D: 'I', E: 'F', G: 'A', I: 'G', K: 'L', L: 'K' }, // row 169
  'AEFGHJKL': { A: 'E', B: 'G', D: 'J', E: 'F', G: 'A', I: 'H', K: 'L', L: 'K' }, // row 170
  'AEFGHIKL': { A: 'E', B: 'G', D: 'I', E: 'F', G: 'A', I: 'H', K: 'L', L: 'K' }, // row 171
  'AEFGHIJL': { A: 'E', B: 'G', D: 'J', E: 'F', G: 'A', I: 'H', K: 'L', L: 'I' }, // row 172
  'AEFGHIJK': { A: 'E', B: 'G', D: 'J', E: 'F', G: 'A', I: 'H', K: 'I', L: 'K' }, // row 173
  'ADGHIJKL': { A: 'H', B: 'J', D: 'I', E: 'D', G: 'A', I: 'G', K: 'L', L: 'K' }, // row 174
  'ADFHIJKL': { A: 'H', B: 'J', D: 'I', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 175
  'ADFGIJKL': { A: 'I', B: 'G', D: 'J', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 176
  'ADFGHJKL': { A: 'H', B: 'G', D: 'J', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 177
  'ADFGHIKL': { A: 'H', B: 'G', D: 'I', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 178
  'ADFGHIJL': { A: 'H', B: 'G', D: 'J', E: 'D', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 179
  'ADFGHIJK': { A: 'H', B: 'G', D: 'J', E: 'D', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 180
  'ADEHIJKL': { A: 'E', B: 'J', D: 'I', E: 'D', G: 'A', I: 'H', K: 'L', L: 'K' }, // row 181
  'ADEGIJKL': { A: 'E', B: 'J', D: 'I', E: 'D', G: 'A', I: 'G', K: 'L', L: 'K' }, // row 182
  'ADEGHJKL': { A: 'E', B: 'G', D: 'J', E: 'D', G: 'A', I: 'H', K: 'L', L: 'K' }, // row 183
  'ADEGHIKL': { A: 'E', B: 'G', D: 'I', E: 'D', G: 'A', I: 'H', K: 'L', L: 'K' }, // row 184
  'ADEGHIJL': { A: 'E', B: 'G', D: 'J', E: 'D', G: 'A', I: 'H', K: 'L', L: 'I' }, // row 185
  'ADEGHIJK': { A: 'E', B: 'G', D: 'J', E: 'D', G: 'A', I: 'H', K: 'I', L: 'K' }, // row 186
  'ADEFIJKL': { A: 'E', B: 'J', D: 'I', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 187
  'ADEFHJKL': { A: 'H', B: 'J', D: 'E', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 188
  'ADEFHIKL': { A: 'H', B: 'E', D: 'I', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 189
  'ADEFHIJL': { A: 'H', B: 'J', D: 'E', E: 'D', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 190
  'ADEFHIJK': { A: 'H', B: 'J', D: 'E', E: 'D', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 191
  'ADEFGJKL': { A: 'E', B: 'G', D: 'J', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 192
  'ADEFGIKL': { A: 'E', B: 'G', D: 'I', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 193
  'ADEFGIJL': { A: 'E', B: 'G', D: 'J', E: 'D', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 194
  'ADEFGIJK': { A: 'E', B: 'G', D: 'J', E: 'D', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 195
  'ADEFGHKL': { A: 'H', B: 'G', D: 'E', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 196
  'ADEFGHJL': { A: 'H', B: 'G', D: 'J', E: 'D', G: 'A', I: 'F', K: 'L', L: 'E' }, // row 197
  'ADEFGHJK': { A: 'H', B: 'G', D: 'J', E: 'D', G: 'A', I: 'F', K: 'E', L: 'K' }, // row 198
  'ADEFGHIL': { A: 'H', B: 'G', D: 'E', E: 'D', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 199
  'ADEFGHIK': { A: 'H', B: 'G', D: 'E', E: 'D', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 200
  'ADEFGHIJ': { A: 'H', B: 'G', D: 'J', E: 'D', G: 'A', I: 'F', K: 'E', L: 'I' }, // row 201
  'ACGHIJKL': { A: 'H', B: 'J', D: 'I', E: 'C', G: 'A', I: 'G', K: 'L', L: 'K' }, // row 202
  'ACFHIJKL': { A: 'H', B: 'J', D: 'I', E: 'C', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 203
  'ACFGIJKL': { A: 'I', B: 'G', D: 'J', E: 'C', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 204
  'ACFGHJKL': { A: 'H', B: 'G', D: 'J', E: 'C', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 205
  'ACFGHIKL': { A: 'H', B: 'G', D: 'I', E: 'C', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 206
  'ACFGHIJL': { A: 'H', B: 'G', D: 'J', E: 'C', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 207
  'ACFGHIJK': { A: 'H', B: 'G', D: 'J', E: 'C', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 208
  'ACEHIJKL': { A: 'E', B: 'J', D: 'I', E: 'C', G: 'A', I: 'H', K: 'L', L: 'K' }, // row 209
  'ACEGIJKL': { A: 'E', B: 'J', D: 'I', E: 'C', G: 'A', I: 'G', K: 'L', L: 'K' }, // row 210
  'ACEGHJKL': { A: 'E', B: 'G', D: 'J', E: 'C', G: 'A', I: 'H', K: 'L', L: 'K' }, // row 211
  'ACEGHIKL': { A: 'E', B: 'G', D: 'I', E: 'C', G: 'A', I: 'H', K: 'L', L: 'K' }, // row 212
  'ACEGHIJL': { A: 'E', B: 'G', D: 'J', E: 'C', G: 'A', I: 'H', K: 'L', L: 'I' }, // row 213
  'ACEGHIJK': { A: 'E', B: 'G', D: 'J', E: 'C', G: 'A', I: 'H', K: 'I', L: 'K' }, // row 214
  'ACEFIJKL': { A: 'E', B: 'J', D: 'I', E: 'C', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 215
  'ACEFHJKL': { A: 'H', B: 'J', D: 'E', E: 'C', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 216
  'ACEFHIKL': { A: 'H', B: 'E', D: 'I', E: 'C', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 217
  'ACEFHIJL': { A: 'H', B: 'J', D: 'E', E: 'C', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 218
  'ACEFHIJK': { A: 'H', B: 'J', D: 'E', E: 'C', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 219
  'ACEFGJKL': { A: 'E', B: 'G', D: 'J', E: 'C', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 220
  'ACEFGIKL': { A: 'E', B: 'G', D: 'I', E: 'C', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 221
  'ACEFGIJL': { A: 'E', B: 'G', D: 'J', E: 'C', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 222
  'ACEFGIJK': { A: 'E', B: 'G', D: 'J', E: 'C', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 223
  'ACEFGHKL': { A: 'H', B: 'G', D: 'E', E: 'C', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 224
  'ACEFGHJL': { A: 'H', B: 'G', D: 'J', E: 'C', G: 'A', I: 'F', K: 'L', L: 'E' }, // row 225
  'ACEFGHJK': { A: 'H', B: 'G', D: 'J', E: 'C', G: 'A', I: 'F', K: 'E', L: 'K' }, // row 226
  'ACEFGHIL': { A: 'H', B: 'G', D: 'E', E: 'C', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 227
  'ACEFGHIK': { A: 'H', B: 'G', D: 'E', E: 'C', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 228
  'ACEFGHIJ': { A: 'H', B: 'G', D: 'J', E: 'C', G: 'A', I: 'F', K: 'E', L: 'I' }, // row 229
  'ACDHIJKL': { A: 'H', B: 'J', D: 'I', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 230
  'ACDGIJKL': { A: 'I', B: 'G', D: 'J', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 231
  'ACDGHJKL': { A: 'H', B: 'G', D: 'J', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 232
  'ACDGHIKL': { A: 'H', B: 'G', D: 'I', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 233
  'ACDGHIJL': { A: 'H', B: 'G', D: 'J', E: 'C', G: 'A', I: 'D', K: 'L', L: 'I' }, // row 234
  'ACDGHIJK': { A: 'H', B: 'G', D: 'J', E: 'C', G: 'A', I: 'D', K: 'I', L: 'K' }, // row 235
  'ACDFIJKL': { A: 'C', B: 'J', D: 'I', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 236
  'ACDFHJKL': { A: 'H', B: 'J', D: 'F', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 237
  'ACDFHIKL': { A: 'H', B: 'F', D: 'I', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 238
  'ACDFHIJL': { A: 'H', B: 'J', D: 'F', E: 'C', G: 'A', I: 'D', K: 'L', L: 'I' }, // row 239
  'ACDFHIJK': { A: 'H', B: 'J', D: 'F', E: 'C', G: 'A', I: 'D', K: 'I', L: 'K' }, // row 240
  'ACDFGJKL': { A: 'C', B: 'G', D: 'J', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 241
  'ACDFGIKL': { A: 'C', B: 'G', D: 'I', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 242
  'ACDFGIJL': { A: 'C', B: 'G', D: 'J', E: 'D', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 243
  'ACDFGIJK': { A: 'C', B: 'G', D: 'J', E: 'D', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 244
  'ACDFGHKL': { A: 'H', B: 'G', D: 'F', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 245
  'ACDFGHJL': { A: 'C', B: 'G', D: 'J', E: 'D', G: 'A', I: 'F', K: 'L', L: 'H' }, // row 246
  'ACDFGHJK': { A: 'H', B: 'G', D: 'J', E: 'C', G: 'A', I: 'F', K: 'D', L: 'K' }, // row 247
  'ACDFGHIL': { A: 'H', B: 'G', D: 'F', E: 'C', G: 'A', I: 'D', K: 'L', L: 'I' }, // row 248
  'ACDFGHIK': { A: 'H', B: 'G', D: 'F', E: 'C', G: 'A', I: 'D', K: 'I', L: 'K' }, // row 249
  'ACDFGHIJ': { A: 'H', B: 'G', D: 'J', E: 'C', G: 'A', I: 'F', K: 'D', L: 'I' }, // row 250
  'ACDEIJKL': { A: 'E', B: 'J', D: 'I', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 251
  'ACDEHJKL': { A: 'H', B: 'J', D: 'E', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 252
  'ACDEHIKL': { A: 'H', B: 'E', D: 'I', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 253
  'ACDEHIJL': { A: 'H', B: 'J', D: 'E', E: 'C', G: 'A', I: 'D', K: 'L', L: 'I' }, // row 254
  'ACDEHIJK': { A: 'H', B: 'J', D: 'E', E: 'C', G: 'A', I: 'D', K: 'I', L: 'K' }, // row 255
  'ACDEGJKL': { A: 'E', B: 'G', D: 'J', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 256
  'ACDEGIKL': { A: 'E', B: 'G', D: 'I', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 257
  'ACDEGIJL': { A: 'E', B: 'G', D: 'J', E: 'C', G: 'A', I: 'D', K: 'L', L: 'I' }, // row 258
  'ACDEGIJK': { A: 'E', B: 'G', D: 'J', E: 'C', G: 'A', I: 'D', K: 'I', L: 'K' }, // row 259
  'ACDEGHKL': { A: 'H', B: 'G', D: 'E', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 260
  'ACDEGHJL': { A: 'H', B: 'G', D: 'J', E: 'C', G: 'A', I: 'D', K: 'L', L: 'E' }, // row 261
  'ACDEGHJK': { A: 'H', B: 'G', D: 'J', E: 'C', G: 'A', I: 'D', K: 'E', L: 'K' }, // row 262
  'ACDEGHIL': { A: 'H', B: 'G', D: 'E', E: 'C', G: 'A', I: 'D', K: 'L', L: 'I' }, // row 263
  'ACDEGHIK': { A: 'H', B: 'G', D: 'E', E: 'C', G: 'A', I: 'D', K: 'I', L: 'K' }, // row 264
  'ACDEGHIJ': { A: 'H', B: 'G', D: 'J', E: 'C', G: 'A', I: 'D', K: 'E', L: 'I' }, // row 265
  'ACDEFJKL': { A: 'C', B: 'J', D: 'E', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 266
  'ACDEFIKL': { A: 'C', B: 'E', D: 'I', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 267
  'ACDEFIJL': { A: 'C', B: 'J', D: 'E', E: 'D', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 268
  'ACDEFIJK': { A: 'C', B: 'J', D: 'E', E: 'D', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 269
  'ACDEFHKL': { A: 'H', B: 'E', D: 'F', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 270
  'ACDEFHJL': { A: 'H', B: 'J', D: 'F', E: 'C', G: 'A', I: 'D', K: 'L', L: 'E' }, // row 271
  'ACDEFHJK': { A: 'H', B: 'J', D: 'E', E: 'C', G: 'A', I: 'F', K: 'D', L: 'K' }, // row 272
  'ACDEFHIL': { A: 'H', B: 'E', D: 'F', E: 'C', G: 'A', I: 'D', K: 'L', L: 'I' }, // row 273
  'ACDEFHIK': { A: 'H', B: 'E', D: 'F', E: 'C', G: 'A', I: 'D', K: 'I', L: 'K' }, // row 274
  'ACDEFHIJ': { A: 'H', B: 'J', D: 'E', E: 'C', G: 'A', I: 'F', K: 'D', L: 'I' }, // row 275
  'ACDEFGKL': { A: 'C', B: 'G', D: 'E', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 276
  'ACDEFGJL': { A: 'C', B: 'G', D: 'J', E: 'D', G: 'A', I: 'F', K: 'L', L: 'E' }, // row 277
  'ACDEFGJK': { A: 'C', B: 'G', D: 'J', E: 'D', G: 'A', I: 'F', K: 'E', L: 'K' }, // row 278
  'ACDEFGIL': { A: 'C', B: 'G', D: 'E', E: 'D', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 279
  'ACDEFGIK': { A: 'C', B: 'G', D: 'E', E: 'D', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 280
  'ACDEFGIJ': { A: 'C', B: 'G', D: 'J', E: 'D', G: 'A', I: 'F', K: 'E', L: 'I' }, // row 281
  'ACDEFGHL': { A: 'H', B: 'G', D: 'F', E: 'C', G: 'A', I: 'D', K: 'L', L: 'E' }, // row 282
  'ACDEFGHK': { A: 'H', B: 'G', D: 'E', E: 'C', G: 'A', I: 'F', K: 'D', L: 'K' }, // row 283
  'ACDEFGHJ': { A: 'H', B: 'G', D: 'J', E: 'C', G: 'A', I: 'F', K: 'D', L: 'E' }, // row 284
  'ACDEFGHI': { A: 'H', B: 'G', D: 'E', E: 'C', G: 'A', I: 'F', K: 'D', L: 'I' }, // row 285
  'ABGHIJKL': { A: 'H', B: 'J', D: 'B', E: 'A', G: 'I', I: 'G', K: 'L', L: 'K' }, // row 286
  'ABFHIJKL': { A: 'H', B: 'J', D: 'B', E: 'A', G: 'I', I: 'F', K: 'L', L: 'K' }, // row 287
  'ABFGIJKL': { A: 'I', B: 'J', D: 'B', E: 'F', G: 'A', I: 'G', K: 'L', L: 'K' }, // row 288
  'ABFGHJKL': { A: 'H', B: 'J', D: 'B', E: 'F', G: 'A', I: 'G', K: 'L', L: 'K' }, // row 289
  'ABFGHIKL': { A: 'H', B: 'G', D: 'B', E: 'A', G: 'I', I: 'F', K: 'L', L: 'K' }, // row 290
  'ABFGHIJL': { A: 'H', B: 'J', D: 'B', E: 'F', G: 'A', I: 'G', K: 'L', L: 'I' }, // row 291
  'ABFGHIJK': { A: 'H', B: 'J', D: 'B', E: 'F', G: 'A', I: 'G', K: 'I', L: 'K' }, // row 292
  'ABEHIJKL': { A: 'E', B: 'J', D: 'B', E: 'A', G: 'I', I: 'H', K: 'L', L: 'K' }, // row 293
  'ABEGIJKL': { A: 'E', B: 'J', D: 'B', E: 'A', G: 'I', I: 'G', K: 'L', L: 'K' }, // row 294
  'ABEGHJKL': { A: 'E', B: 'J', D: 'B', E: 'A', G: 'H', I: 'G', K: 'L', L: 'K' }, // row 295
  'ABEGHIKL': { A: 'E', B: 'G', D: 'B', E: 'A', G: 'I', I: 'H', K: 'L', L: 'K' }, // row 296
  'ABEGHIJL': { A: 'E', B: 'J', D: 'B', E: 'A', G: 'H', I: 'G', K: 'L', L: 'I' }, // row 297
  'ABEGHIJK': { A: 'E', B: 'J', D: 'B', E: 'A', G: 'H', I: 'G', K: 'I', L: 'K' }, // row 298
  'ABEFIJKL': { A: 'E', B: 'J', D: 'B', E: 'A', G: 'I', I: 'F', K: 'L', L: 'K' }, // row 299
  'ABEFHJKL': { A: 'E', B: 'J', D: 'B', E: 'F', G: 'A', I: 'H', K: 'L', L: 'K' }, // row 300
  'ABEFHIKL': { A: 'E', B: 'I', D: 'B', E: 'F', G: 'A', I: 'H', K: 'L', L: 'K' }, // row 301
  'ABEFHIJL': { A: 'E', B: 'J', D: 'B', E: 'F', G: 'A', I: 'H', K: 'L', L: 'I' }, // row 302
  'ABEFHIJK': { A: 'E', B: 'J', D: 'B', E: 'F', G: 'A', I: 'H', K: 'I', L: 'K' }, // row 303
  'ABEFGJKL': { A: 'E', B: 'J', D: 'B', E: 'F', G: 'A', I: 'G', K: 'L', L: 'K' }, // row 304
  'ABEFGIKL': { A: 'E', B: 'G', D: 'B', E: 'A', G: 'I', I: 'F', K: 'L', L: 'K' }, // row 305
  'ABEFGIJL': { A: 'E', B: 'J', D: 'B', E: 'F', G: 'A', I: 'G', K: 'L', L: 'I' }, // row 306
  'ABEFGIJK': { A: 'E', B: 'J', D: 'B', E: 'F', G: 'A', I: 'G', K: 'I', L: 'K' }, // row 307
  'ABEFGHKL': { A: 'E', B: 'G', D: 'B', E: 'F', G: 'A', I: 'H', K: 'L', L: 'K' }, // row 308
  'ABEFGHJL': { A: 'H', B: 'J', D: 'B', E: 'F', G: 'A', I: 'G', K: 'L', L: 'E' }, // row 309
  'ABEFGHJK': { A: 'H', B: 'J', D: 'B', E: 'F', G: 'A', I: 'G', K: 'E', L: 'K' }, // row 310
  'ABEFGHIL': { A: 'E', B: 'G', D: 'B', E: 'F', G: 'A', I: 'H', K: 'L', L: 'I' }, // row 311
  'ABEFGHIK': { A: 'E', B: 'G', D: 'B', E: 'F', G: 'A', I: 'H', K: 'I', L: 'K' }, // row 312
  'ABEFGHIJ': { A: 'H', B: 'J', D: 'B', E: 'F', G: 'A', I: 'G', K: 'E', L: 'I' }, // row 313
  'ABDHIJKL': { A: 'I', B: 'J', D: 'B', E: 'D', G: 'A', I: 'H', K: 'L', L: 'K' }, // row 314
  'ABDGIJKL': { A: 'I', B: 'J', D: 'B', E: 'D', G: 'A', I: 'G', K: 'L', L: 'K' }, // row 315
  'ABDGHJKL': { A: 'H', B: 'J', D: 'B', E: 'D', G: 'A', I: 'G', K: 'L', L: 'K' }, // row 316
  'ABDGHIKL': { A: 'I', B: 'G', D: 'B', E: 'D', G: 'A', I: 'H', K: 'L', L: 'K' }, // row 317
  'ABDGHIJL': { A: 'H', B: 'J', D: 'B', E: 'D', G: 'A', I: 'G', K: 'L', L: 'I' }, // row 318
  'ABDGHIJK': { A: 'H', B: 'J', D: 'B', E: 'D', G: 'A', I: 'G', K: 'I', L: 'K' }, // row 319
  'ABDFIJKL': { A: 'I', B: 'J', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 320
  'ABDFHJKL': { A: 'H', B: 'J', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 321
  'ABDFHIKL': { A: 'H', B: 'I', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 322
  'ABDFHIJL': { A: 'H', B: 'J', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 323
  'ABDFHIJK': { A: 'H', B: 'J', D: 'B', E: 'D', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 324
  'ABDFGJKL': { A: 'F', B: 'J', D: 'B', E: 'D', G: 'A', I: 'G', K: 'L', L: 'K' }, // row 325
  'ABDFGIKL': { A: 'I', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 326
  'ABDFGIJL': { A: 'F', B: 'J', D: 'B', E: 'D', G: 'A', I: 'G', K: 'L', L: 'I' }, // row 327
  'ABDFGIJK': { A: 'F', B: 'J', D: 'B', E: 'D', G: 'A', I: 'G', K: 'I', L: 'K' }, // row 328
  'ABDFGHKL': { A: 'H', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 329
  'ABDFGHJL': { A: 'H', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'J' }, // row 330
  'ABDFGHJK': { A: 'H', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'J', L: 'K' }, // row 331
  'ABDFGHIL': { A: 'H', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 332
  'ABDFGHIK': { A: 'H', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 333
  'ABDFGHIJ': { A: 'H', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'I', L: 'J' }, // row 334
  'ABDEIJKL': { A: 'E', B: 'J', D: 'B', E: 'A', G: 'I', I: 'D', K: 'L', L: 'K' }, // row 335
  'ABDEHJKL': { A: 'E', B: 'J', D: 'B', E: 'D', G: 'A', I: 'H', K: 'L', L: 'K' }, // row 336
  'ABDEHIKL': { A: 'E', B: 'I', D: 'B', E: 'D', G: 'A', I: 'H', K: 'L', L: 'K' }, // row 337
  'ABDEHIJL': { A: 'E', B: 'J', D: 'B', E: 'D', G: 'A', I: 'H', K: 'L', L: 'I' }, // row 338
  'ABDEHIJK': { A: 'E', B: 'J', D: 'B', E: 'D', G: 'A', I: 'H', K: 'I', L: 'K' }, // row 339
  'ABDEGJKL': { A: 'E', B: 'J', D: 'B', E: 'D', G: 'A', I: 'G', K: 'L', L: 'K' }, // row 340
  'ABDEGIKL': { A: 'E', B: 'G', D: 'B', E: 'A', G: 'I', I: 'D', K: 'L', L: 'K' }, // row 341
  'ABDEGIJL': { A: 'E', B: 'J', D: 'B', E: 'D', G: 'A', I: 'G', K: 'L', L: 'I' }, // row 342
  'ABDEGIJK': { A: 'E', B: 'J', D: 'B', E: 'D', G: 'A', I: 'G', K: 'I', L: 'K' }, // row 343
  'ABDEGHKL': { A: 'E', B: 'G', D: 'B', E: 'D', G: 'A', I: 'H', K: 'L', L: 'K' }, // row 344
  'ABDEGHJL': { A: 'H', B: 'J', D: 'B', E: 'D', G: 'A', I: 'G', K: 'L', L: 'E' }, // row 345
  'ABDEGHJK': { A: 'H', B: 'J', D: 'B', E: 'D', G: 'A', I: 'G', K: 'E', L: 'K' }, // row 346
  'ABDEGHIL': { A: 'E', B: 'G', D: 'B', E: 'D', G: 'A', I: 'H', K: 'L', L: 'I' }, // row 347
  'ABDEGHIK': { A: 'E', B: 'G', D: 'B', E: 'D', G: 'A', I: 'H', K: 'I', L: 'K' }, // row 348
  'ABDEGHIJ': { A: 'H', B: 'J', D: 'B', E: 'D', G: 'A', I: 'G', K: 'E', L: 'I' }, // row 349
  'ABDEFJKL': { A: 'E', B: 'J', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 350
  'ABDEFIKL': { A: 'E', B: 'I', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 351
  'ABDEFIJL': { A: 'E', B: 'J', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 352
  'ABDEFIJK': { A: 'E', B: 'J', D: 'B', E: 'D', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 353
  'ABDEFHKL': { A: 'H', B: 'E', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 354
  'ABDEFHJL': { A: 'H', B: 'J', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'E' }, // row 355
  'ABDEFHJK': { A: 'H', B: 'J', D: 'B', E: 'D', G: 'A', I: 'F', K: 'E', L: 'K' }, // row 356
  'ABDEFHIL': { A: 'H', B: 'E', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 357
  'ABDEFHIK': { A: 'H', B: 'E', D: 'B', E: 'D', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 358
  'ABDEFHIJ': { A: 'H', B: 'J', D: 'B', E: 'D', G: 'A', I: 'F', K: 'E', L: 'I' }, // row 359
  'ABDEFGKL': { A: 'E', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 360
  'ABDEFGJL': { A: 'E', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'J' }, // row 361
  'ABDEFGJK': { A: 'E', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'J', L: 'K' }, // row 362
  'ABDEFGIL': { A: 'E', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 363
  'ABDEFGIK': { A: 'E', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 364
  'ABDEFGIJ': { A: 'E', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'I', L: 'J' }, // row 365
  'ABDEFGHL': { A: 'H', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'E' }, // row 366
  'ABDEFGHK': { A: 'H', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'E', L: 'K' }, // row 367
  'ABDEFGHJ': { A: 'H', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'E', L: 'J' }, // row 368
  'ABDEFGHI': { A: 'H', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'E', L: 'I' }, // row 369
  'ABCHIJKL': { A: 'I', B: 'J', D: 'B', E: 'C', G: 'A', I: 'H', K: 'L', L: 'K' }, // row 370
  'ABCGIJKL': { A: 'I', B: 'J', D: 'B', E: 'C', G: 'A', I: 'G', K: 'L', L: 'K' }, // row 371
  'ABCGHJKL': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'A', I: 'G', K: 'L', L: 'K' }, // row 372
  'ABCGHIKL': { A: 'I', B: 'G', D: 'B', E: 'C', G: 'A', I: 'H', K: 'L', L: 'K' }, // row 373
  'ABCGHIJL': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'A', I: 'G', K: 'L', L: 'I' }, // row 374
  'ABCGHIJK': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'A', I: 'G', K: 'I', L: 'K' }, // row 375
  'ABCFIJKL': { A: 'I', B: 'J', D: 'B', E: 'C', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 376
  'ABCFHJKL': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 377
  'ABCFHIKL': { A: 'H', B: 'I', D: 'B', E: 'C', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 378
  'ABCFHIJL': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 379
  'ABCFHIJK': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 380
  'ABCFGJKL': { A: 'C', B: 'J', D: 'B', E: 'F', G: 'A', I: 'G', K: 'L', L: 'K' }, // row 381
  'ABCFGIKL': { A: 'I', B: 'G', D: 'B', E: 'C', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 382
  'ABCFGIJL': { A: 'C', B: 'J', D: 'B', E: 'F', G: 'A', I: 'G', K: 'L', L: 'I' }, // row 383
  'ABCFGIJK': { A: 'C', B: 'J', D: 'B', E: 'F', G: 'A', I: 'G', K: 'I', L: 'K' }, // row 384
  'ABCFGHKL': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 385
  'ABCFGHJL': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'F', K: 'L', L: 'J' }, // row 386
  'ABCFGHJK': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'F', K: 'J', L: 'K' }, // row 387
  'ABCFGHIL': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 388
  'ABCFGHIK': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 389
  'ABCFGHIJ': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'F', K: 'I', L: 'J' }, // row 390
  'ABCEIJKL': { A: 'E', B: 'J', D: 'B', E: 'A', G: 'I', I: 'C', K: 'L', L: 'K' }, // row 391
  'ABCEHJKL': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'A', I: 'H', K: 'L', L: 'K' }, // row 392
  'ABCEHIKL': { A: 'E', B: 'I', D: 'B', E: 'C', G: 'A', I: 'H', K: 'L', L: 'K' }, // row 393
  'ABCEHIJL': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'A', I: 'H', K: 'L', L: 'I' }, // row 394
  'ABCEHIJK': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'A', I: 'H', K: 'I', L: 'K' }, // row 395
  'ABCEGJKL': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'A', I: 'G', K: 'L', L: 'K' }, // row 396
  'ABCEGIKL': { A: 'E', B: 'G', D: 'B', E: 'A', G: 'I', I: 'C', K: 'L', L: 'K' }, // row 397
  'ABCEGIJL': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'A', I: 'G', K: 'L', L: 'I' }, // row 398
  'ABCEGIJK': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'A', I: 'G', K: 'I', L: 'K' }, // row 399
  'ABCEGHKL': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'A', I: 'H', K: 'L', L: 'K' }, // row 400
  'ABCEGHJL': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'A', I: 'G', K: 'L', L: 'E' }, // row 401
  'ABCEGHJK': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'A', I: 'G', K: 'E', L: 'K' }, // row 402
  'ABCEGHIL': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'A', I: 'H', K: 'L', L: 'I' }, // row 403
  'ABCEGHIK': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'A', I: 'H', K: 'I', L: 'K' }, // row 404
  'ABCEGHIJ': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'A', I: 'G', K: 'E', L: 'I' }, // row 405
  'ABCEFJKL': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 406
  'ABCEFIKL': { A: 'E', B: 'I', D: 'B', E: 'C', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 407
  'ABCEFIJL': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 408
  'ABCEFIJK': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 409
  'ABCEFHKL': { A: 'H', B: 'E', D: 'B', E: 'C', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 410
  'ABCEFHJL': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'A', I: 'F', K: 'L', L: 'E' }, // row 411
  'ABCEFHJK': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'A', I: 'F', K: 'E', L: 'K' }, // row 412
  'ABCEFHIL': { A: 'H', B: 'E', D: 'B', E: 'C', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 413
  'ABCEFHIK': { A: 'H', B: 'E', D: 'B', E: 'C', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 414
  'ABCEFHIJ': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'A', I: 'F', K: 'E', L: 'I' }, // row 415
  'ABCEFGKL': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 416
  'ABCEFGJL': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'A', I: 'F', K: 'L', L: 'J' }, // row 417
  'ABCEFGJK': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'A', I: 'F', K: 'J', L: 'K' }, // row 418
  'ABCEFGIL': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 419
  'ABCEFGIK': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 420
  'ABCEFGIJ': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'A', I: 'F', K: 'I', L: 'J' }, // row 421
  'ABCEFGHL': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'F', K: 'L', L: 'E' }, // row 422
  'ABCEFGHK': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'F', K: 'E', L: 'K' }, // row 423
  'ABCEFGHJ': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'F', K: 'E', L: 'J' }, // row 424
  'ABCEFGHI': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'F', K: 'E', L: 'I' }, // row 425
  'ABCDIJKL': { A: 'I', B: 'J', D: 'B', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 426
  'ABCDHJKL': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 427
  'ABCDHIKL': { A: 'H', B: 'I', D: 'B', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 428
  'ABCDHIJL': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'A', I: 'D', K: 'L', L: 'I' }, // row 429
  'ABCDHIJK': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'A', I: 'D', K: 'I', L: 'K' }, // row 430
  'ABCDGJKL': { A: 'C', B: 'J', D: 'B', E: 'D', G: 'A', I: 'G', K: 'L', L: 'K' }, // row 431
  'ABCDGIKL': { A: 'I', B: 'G', D: 'B', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 432
  'ABCDGIJL': { A: 'C', B: 'J', D: 'B', E: 'D', G: 'A', I: 'G', K: 'L', L: 'I' }, // row 433
  'ABCDGIJK': { A: 'C', B: 'J', D: 'B', E: 'D', G: 'A', I: 'G', K: 'I', L: 'K' }, // row 434
  'ABCDGHKL': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 435
  'ABCDGHJL': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'D', K: 'L', L: 'J' }, // row 436
  'ABCDGHJK': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'D', K: 'J', L: 'K' }, // row 437
  'ABCDGHIL': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'D', K: 'L', L: 'I' }, // row 438
  'ABCDGHIK': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'D', K: 'I', L: 'K' }, // row 439
  'ABCDGHIJ': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'D', K: 'I', L: 'J' }, // row 440
  'ABCDFJKL': { A: 'C', B: 'J', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 441
  'ABCDFIKL': { A: 'C', B: 'I', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 442
  'ABCDFIJL': { A: 'C', B: 'J', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 443
  'ABCDFIJK': { A: 'C', B: 'J', D: 'B', E: 'D', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 444
  'ABCDFHKL': { A: 'H', B: 'F', D: 'B', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 445
  'ABCDFHJL': { A: 'C', B: 'J', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'H' }, // row 446
  'ABCDFHJK': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'A', I: 'F', K: 'D', L: 'K' }, // row 447
  'ABCDFHIL': { A: 'H', B: 'F', D: 'B', E: 'C', G: 'A', I: 'D', K: 'L', L: 'I' }, // row 448
  'ABCDFHIK': { A: 'H', B: 'F', D: 'B', E: 'C', G: 'A', I: 'D', K: 'I', L: 'K' }, // row 449
  'ABCDFHIJ': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'A', I: 'F', K: 'D', L: 'I' }, // row 450
  'ABCDFGKL': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 451
  'ABCDFGJL': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'J' }, // row 452
  'ABCDFGJK': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'J', L: 'K' }, // row 453
  'ABCDFGIL': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 454
  'ABCDFGIK': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 455
  'ABCDFGIJ': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'I', L: 'J' }, // row 456
  'ABCDFGHL': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'H' }, // row 457
  'ABCDFGHK': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'F', K: 'D', L: 'K' }, // row 458
  'ABCDFGHJ': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'F', K: 'D', L: 'J' }, // row 459
  'ABCDFGHI': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'F', K: 'D', L: 'I' }, // row 460
  'ABCDEJKL': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 461
  'ABCDEIKL': { A: 'E', B: 'I', D: 'B', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 462
  'ABCDEIJL': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'A', I: 'D', K: 'L', L: 'I' }, // row 463
  'ABCDEIJK': { A: 'E', B: 'J', D: 'B', E: 'C', G: 'A', I: 'D', K: 'I', L: 'K' }, // row 464
  'ABCDEHKL': { A: 'H', B: 'E', D: 'B', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 465
  'ABCDEHJL': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'A', I: 'D', K: 'L', L: 'E' }, // row 466
  'ABCDEHJK': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'A', I: 'D', K: 'E', L: 'K' }, // row 467
  'ABCDEHIL': { A: 'H', B: 'E', D: 'B', E: 'C', G: 'A', I: 'D', K: 'L', L: 'I' }, // row 468
  'ABCDEHIK': { A: 'H', B: 'E', D: 'B', E: 'C', G: 'A', I: 'D', K: 'I', L: 'K' }, // row 469
  'ABCDEHIJ': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'A', I: 'D', K: 'E', L: 'I' }, // row 470
  'ABCDEGKL': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'A', I: 'D', K: 'L', L: 'K' }, // row 471
  'ABCDEGJL': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'A', I: 'D', K: 'L', L: 'J' }, // row 472
  'ABCDEGJK': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'A', I: 'D', K: 'J', L: 'K' }, // row 473
  'ABCDEGIL': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'A', I: 'D', K: 'L', L: 'I' }, // row 474
  'ABCDEGIK': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'A', I: 'D', K: 'I', L: 'K' }, // row 475
  'ABCDEGIJ': { A: 'E', B: 'G', D: 'B', E: 'C', G: 'A', I: 'D', K: 'I', L: 'J' }, // row 476
  'ABCDEGHL': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'D', K: 'L', L: 'E' }, // row 477
  'ABCDEGHK': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'D', K: 'E', L: 'K' }, // row 478
  'ABCDEGHJ': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'D', K: 'E', L: 'J' }, // row 479
  'ABCDEGHI': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'D', K: 'E', L: 'I' }, // row 480
  'ABCDEFKL': { A: 'C', B: 'E', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'K' }, // row 481
  'ABCDEFJL': { A: 'C', B: 'J', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'E' }, // row 482
  'ABCDEFJK': { A: 'C', B: 'J', D: 'B', E: 'D', G: 'A', I: 'F', K: 'E', L: 'K' }, // row 483
  'ABCDEFIL': { A: 'C', B: 'E', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'I' }, // row 484
  'ABCDEFIK': { A: 'C', B: 'E', D: 'B', E: 'D', G: 'A', I: 'F', K: 'I', L: 'K' }, // row 485
  'ABCDEFIJ': { A: 'C', B: 'J', D: 'B', E: 'D', G: 'A', I: 'F', K: 'E', L: 'I' }, // row 486
  'ABCDEFHL': { A: 'H', B: 'F', D: 'B', E: 'C', G: 'A', I: 'D', K: 'L', L: 'E' }, // row 487
  'ABCDEFHK': { A: 'H', B: 'E', D: 'B', E: 'C', G: 'A', I: 'F', K: 'D', L: 'K' }, // row 488
  'ABCDEFHJ': { A: 'H', B: 'J', D: 'B', E: 'C', G: 'A', I: 'F', K: 'D', L: 'E' }, // row 489
  'ABCDEFHI': { A: 'H', B: 'E', D: 'B', E: 'C', G: 'A', I: 'F', K: 'D', L: 'I' }, // row 490
  'ABCDEFGL': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'L', L: 'E' }, // row 491
  'ABCDEFGK': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'E', L: 'K' }, // row 492
  'ABCDEFGJ': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'E', L: 'J' }, // row 493
  'ABCDEFGI': { A: 'C', B: 'G', D: 'B', E: 'D', G: 'A', I: 'F', K: 'E', L: 'I' }, // row 494
  'ABCDEFGH': { A: 'H', B: 'G', D: 'B', E: 'C', G: 'A', I: 'F', K: 'D', L: 'E' }, // row 495
};
